### ISSUE TITLE
How to define a filter without created_at

### ISSUE THREAD

**Issue by Misagh90** [ambengers/laravel-query-filter#21]
I created a model without timestamps `(public $timestamps = false;)` but I have an error for returning resualt via filter:

> Column not found: 1054 Unknown column 'created_at' in 'order clause'

How to solve this error without timestamps in my filter?

**Comment by ambengers** [comment]
@Misagh90 I just added a couple of tests to make sure the package works without issues on models that do not have timestamps.

Can you please provide a code snippet to replicate your issue?

**Comment by ambengers** [comment]
@Misagh90 Also, feel free to open a PR for this issue if you have a solution already.
