### ISSUE TITLE
Livewire v3 compatibility

### ISSUE THREAD

**Issue by Misagh90** [ambengers/laravel-query-filter#26]
Hi,
I tried Query filter with Livewire V3 & it is not compatible, especially with a new method of Livewire Pagination.

**Comment by MohammaddReza** [comment]
I have the same problem with livewire pagination. The queries work in the address but pagination buttons do not work.
livewire 2 and 3 pagination methods are different.

**Comment by ambengers** [comment]
@Misagh90 I don't personally use Livewire V3 on any of my projects right now so I might not be able to get the package to support it immediately.

Feel free to submit a PR if you want to.
